[2022-08-29 17:59:38,786] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-04-10T06:00:00+00:00 [queued]>
[2022-08-29 17:59:38,808] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-04-10T06:00:00+00:00 [queued]>
[2022-08-29 17:59:38,809] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 17:59:38,810] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-08-29 17:59:38,812] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 17:59:38,862] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): entry_task2> on 2021-04-10 06:00:00+00:00
[2022-08-29 17:59:38,877] {standard_task_runner.py:52} INFO - Started process 3322 to run task
[2022-08-29 17:59:38,895] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'h1b_lca_data_v3', 'entry_task2', 'scheduled__2021-04-10T06:00:00+00:00', '--job-id', '1623', '--raw', '--subdir', 'DAGS_FOLDER/upload_h1b_data_to_gcp.py', '--cfg-path', '/tmp/tmpmiz8m7kp', '--error-file', '/tmp/tmprmwemda3']
[2022-08-29 17:59:38,900] {standard_task_runner.py:77} INFO - Job 1623: Subtask entry_task2
[2022-08-29 17:59:39,033] {logging_mixin.py:109} INFO - Running <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-04-10T06:00:00+00:00 [running]> on host f153c6531160
[2022-08-29 17:59:39,129] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=h1b_lca_data_v3
AIRFLOW_CTX_TASK_ID=entry_task2
AIRFLOW_CTX_EXECUTION_DATE=2021-04-10T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-10T06:00:00+00:00
[2022-08-29 17:59:39,134] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-29 17:59:39,136] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "2"']
[2022-08-29 17:59:39,161] {subprocess.py:85} INFO - Output:
[2022-08-29 17:59:39,162] {subprocess.py:89} INFO - 2
[2022-08-29 17:59:39,164] {subprocess.py:93} INFO - Command exited with return code 0
[2022-08-29 17:59:39,214] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=h1b_lca_data_v3, task_id=entry_task2, execution_date=20210410T060000, start_date=20220829T175938, end_date=20220829T175939
[2022-08-29 17:59:39,273] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-29 17:59:39,354] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
