[2022-08-29 18:42:02,469] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-29 18:42:02,488] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-29 18:42:02,490] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 18:42:02,492] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-08-29 18:42:02,493] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 18:42:02,522] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): entry_task2> on 2021-01-10 06:00:00+00:00
[2022-08-29 18:42:02,537] {standard_task_runner.py:52} INFO - Started process 5278 to run task
[2022-08-29 18:42:02,558] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'h1b_lca_data_v3', 'entry_task2', 'scheduled__2021-01-10T06:00:00+00:00', '--job-id', '1655', '--raw', '--subdir', 'DAGS_FOLDER/upload_h1b_data_to_gcp.py', '--cfg-path', '/tmp/tmpv_0mt3br', '--error-file', '/tmp/tmpihy_8al9']
[2022-08-29 18:42:02,560] {standard_task_runner.py:77} INFO - Job 1655: Subtask entry_task2
[2022-08-29 18:42:02,729] {logging_mixin.py:109} INFO - Running <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-01-10T06:00:00+00:00 [running]> on host f153c6531160
[2022-08-29 18:42:02,838] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=h1b_lca_data_v3
AIRFLOW_CTX_TASK_ID=entry_task2
AIRFLOW_CTX_EXECUTION_DATE=2021-01-10T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-10T06:00:00+00:00
[2022-08-29 18:42:02,845] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-29 18:42:02,848] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "None"']
[2022-08-29 18:42:02,867] {subprocess.py:85} INFO - Output:
[2022-08-29 18:42:02,870] {subprocess.py:89} INFO - None
[2022-08-29 18:42:02,872] {subprocess.py:93} INFO - Command exited with return code 0
[2022-08-29 18:42:02,941] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=h1b_lca_data_v3, task_id=entry_task2, execution_date=20210110T060000, start_date=20220829T184202, end_date=20220829T184202
[2022-08-29 18:42:03,018] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-29 18:42:03,147] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
