[2022-08-29 18:53:05,336] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v4.download_data_task scheduled__2021-07-10T06:00:00+00:00 [queued]>
[2022-08-29 18:53:05,360] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v4.download_data_task scheduled__2021-07-10T06:00:00+00:00 [queued]>
[2022-08-29 18:53:05,361] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 18:53:05,362] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-08-29 18:53:05,364] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 18:53:05,388] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_data_task> on 2021-07-10 06:00:00+00:00
[2022-08-29 18:53:05,402] {standard_task_runner.py:52} INFO - Started process 5900 to run task
[2022-08-29 18:53:05,420] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'h1b_lca_data_v4', 'download_data_task', 'scheduled__2021-07-10T06:00:00+00:00', '--job-id', '1693', '--raw', '--subdir', 'DAGS_FOLDER/upload_h1b_data_to_gcp.py', '--cfg-path', '/tmp/tmpnu652wpa', '--error-file', '/tmp/tmpm5kniuyu']
[2022-08-29 18:53:05,422] {standard_task_runner.py:77} INFO - Job 1693: Subtask download_data_task
[2022-08-29 18:53:05,549] {logging_mixin.py:109} INFO - Running <TaskInstance: h1b_lca_data_v4.download_data_task scheduled__2021-07-10T06:00:00+00:00 [running]> on host f153c6531160
[2022-08-29 18:53:05,620] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-29 18:53:05,704] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=h1b_lca_data_v4
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-10T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-10T06:00:00+00:00
[2022-08-29 18:53:05,711] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-29 18:53:05,716] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://www.dol.gov/sites/dolgov/files/ETA/oflc/pdfs/LCA_Disclosure_Data_FY2021_Q3.xlsx>/opt/***/LCA_Disclosure_Data_FY2021_Q3.xlsx']
[2022-08-29 18:53:05,754] {subprocess.py:85} INFO - Output:
[2022-08-29 18:53:20,824] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-08-29 18:53:20,846] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 5900. PIDs of all processes in the group: [5901, 5902, 5900]
[2022-08-29 18:53:20,850] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 5900
[2022-08-29 18:53:20,867] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-29 18:53:20,871] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-08-29 18:53:20,897] {process_utils.py:70} INFO - Process psutil.Process(pid=5902, status='terminated', started='18:53:04') (5902) terminated with exit code None
[2022-08-29 18:53:21,086] {process_utils.py:70} INFO - Process psutil.Process(pid=5901, status='terminated', started='18:53:04') (5901) terminated with exit code None
[2022-08-29 18:53:21,088] {process_utils.py:70} INFO - Process psutil.Process(pid=5900, status='terminated', exitcode=0, started='18:53:04') (5900) terminated with exit code 0
