[2022-08-25 21:33:39,693] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data.format_csv_to_parquet_task scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-25 21:33:39,712] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data.format_csv_to_parquet_task scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-25 21:33:39,714] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-25 21:33:39,715] {taskinstance.py:1239} INFO - Starting attempt 6 of 6
[2022-08-25 21:33:39,716] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-25 21:33:39,733] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_csv_to_parquet_task> on 2021-01-10 06:00:00+00:00
[2022-08-25 21:33:39,743] {standard_task_runner.py:52} INFO - Started process 3320 to run task
[2022-08-25 21:33:39,748] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'h1b_lca_data', 'format_csv_to_parquet_task', 'scheduled__2021-01-10T06:00:00+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/upload_h1b_data_to_gcp.py', '--cfg-path', '/tmp/tmp0ndo3u0o', '--error-file', '/tmp/tmp_etpwkm6']
[2022-08-25 21:33:39,749] {standard_task_runner.py:77} INFO - Job 335: Subtask format_csv_to_parquet_task
[2022-08-25 21:33:39,820] {logging_mixin.py:109} INFO - Running <TaskInstance: h1b_lca_data.format_csv_to_parquet_task scheduled__2021-01-10T06:00:00+00:00 [running]> on host c8cac1ea6d9c
[2022-08-25 21:33:39,862] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-25 21:33:39,884] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=h1b_lca_data
AIRFLOW_CTX_TASK_ID=format_csv_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-10T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-10T06:00:00+00:00
[2022-08-25 21:33:39,901] {logging_mixin.py:109} INFO - Source file to be fetched for format_csv_to_parquet:  /opt/***/LCA_Disclosure_Data_FY2021_Q1.csv
[2022-08-25 21:33:39,902] {logging_mixin.py:109} INFO - Source file: /opt/***/LCA_Disclosure_Data_FY2021_Q1.csv
[2022-08-25 21:33:41,569] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:185: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-08-25 21:33:41,916] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_h1b_data_to_gcp.py", line 90, in format_csv_to_parquet
    table = pq.Table.from_pandas(df)
AttributeError: module 'pyarrow.parquet' has no attribute 'Table'
[2022-08-25 21:33:41,946] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=h1b_lca_data, task_id=format_csv_to_parquet_task, execution_date=20210110T060000, start_date=20220825T213339, end_date=20220825T213341
[2022-08-25 21:33:41,979] {standard_task_runner.py:92} ERROR - Failed to execute job 335 for task format_csv_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_h1b_data_to_gcp.py", line 90, in format_csv_to_parquet
    table = pq.Table.from_pandas(df)
AttributeError: module 'pyarrow.parquet' has no attribute 'Table'
[2022-08-25 21:33:42,060] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-25 21:33:42,100] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
